# Generated by Django 4.2.18 on 2025-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bascket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bascket',
            managers=[
            ],
        ),
    ]
