# Generated by Django 4.2.18 on 2025-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bascket', '0002_alter_bascket_managers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bascket',
            table='bascket',
        ),
    ]
